name: Build and Release

on:
  push:
    tags:
      - 'r*' # Only triggers when you push a tag starting with 'r' (e.g. r140)

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            qt_arch: win64_mingw81
          - os: ubuntu-22.04
            qt_arch: gcc_64
          - os: macos-15-intel
            qt_arch: clang_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '5.15.2'
          tools: ${{ runner.os == 'Windows' && 'tools_mingw81' || '' }}
          arch: ${{ matrix.qt_arch }}
          modules: 'qtquick3d'

      - name: Build Project (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          mkdir build_assets
          cd build_assets
          set PATH=%IQTA_TOOLS%/mingw810_64/bin;%PATH%
          qmake ..\FSModTool.pro CONFIG+=release
          mingw32-make -j2

      - name: Build Project (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mkdir build_assets
          cd build_assets
          qmake ../FSModTool.pro CONFIG+=release
          if [ "$RUNNER_OS" == "macOS" ]; then
            make -j$(sysctl -n hw.ncpu)
          else
            make -j$(nproc)
          fi

      - name: Package Windows (win64)
        if: runner.os == 'Windows'
        shell: bash
        run: mv FSModTool_Release.zip FSModTool-${{ github.ref_name }}-windows-x86_64.zip

      - name: Package Linux (lin64 & AppImage)
        if: runner.os == 'Linux'
        shell: bash
        env: 
          APPIMAGE_EXTRACT_AND_RUN: 1
        run: |
          sudo apt-get update && sudo apt-get install -y libxcb-util1 zip imagemagick
          mv FSModTool_Release.tar.gz FSModTool-${{ github.ref_name }}-linux-x86_64.tar.gz
          #AppImage
          convert KFModTool.ico[0] build_assets/FSModTool.png
          wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          echo -e "[Desktop Entry]\nType=Application\nName=FSModTool\nExec=FSModTool\nIcon=FSModTool\nCategories=Development;" > build_assets/FSModTool.desktop
          cd build_assets
          export VERSION=${{ github.ref_name }}
          ../linuxdeployqt-continuous-x86_64.AppImage FSModTool -appimage -unsupported-allow-new-glibc
          cd ..
          mv FSModTool-*-x86_64.AppImage FSModTool-${{ github.ref_name }}-x86_64.AppImage
          zip FSModTool-${{ github.ref_name }}-x86_64-AppImage.zip FSModTool-${{ github.ref_name }}-x86_64.AppImage

      - name: Package macOS (mac64)
        if: runner.os == 'macOS'
        shell: bash
        run: mv FSModTool_Release.zip FSModTool-${{ github.ref_name }}-macos-x86_64.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: assets-${{ matrix.os }}
          path: |
            FSModTool-*.zip
            FSModTool-*.tar.gz

  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_assets
          merge-multiple: true

      - name: Create GitHub Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          prerelease: false
          title: "FSModTool ${{ github.ref_name }}"
          files: |
            release_assets/FSModTool-*
